### ISSUE TITLE
Document common TLS/SSL issues and solutions

### ISSUE THREAD

**Issue by felixbarny** [elastic/apm-agent-java#1330]
Where applicable, also log more diagnostics information when an SSL issue occurs

**Comment by eyalkoren** [comment]
Documentation-wise, the process is:
- [x] Java agent docs with links to existing SSL documentation in server - #1348 
- [x] Backporting to Java Agent 1.x - #1353 
- [x] Adding server docs - elastic/apm-server#4086
- [ ] Backporting server docs - elastic/apm-server#4103 (PR in review, not yet merged)
- [ ] Updating links in the Java Agent docs to the accurate new server doc sections

Diagnostics: 
- [ ] Whenever a related Exception occurs when creating a connection with APM server, we will print some relevant info, like - `javax.net.ssl.SSLSocketFactory#getDefaultCipherSuites` and `javax.net.ssl.SSLSocketFactory#getSupportedCipherSuites`
