### ISSUE TITLE
Migrate plugins to indy plugins

### ISSUE THREAD

**Issue by felixbarny** [elastic/apm-agent-java#1337]
A meta-issue that tracks the migration

- [x] apm-apache-httpclient-plugin https://github.com/elastic/apm-agent-java/pull/1349
- [x] apm-api-plugin https://github.com/elastic/apm-agent-java/pull/1411
- [x] apm-asynchttpclient-plugin elastic/apm-agent-java#1351
- [x] apm-bootdelegation-plugin N/A - might be removed once all plugins have been migrated to indy plugins
- [x] apm-dubbo-plugin https://github.com/elastic/apm-agent-java/pull/2087
- [x] apm-error-logging-plugin https://github.com/elastic/apm-agent-java/pull/1362
- [x] apm-es-restclient-plugin #2088
- [x] apm-grails-plugin https://github.com/elastic/apm-agent-java/pull/1371
- [x] apm-grpc https://github.com/elastic/apm-agent-java/issues/1358
- [x] apm-hibernate-search-plugin https://github.com/elastic/apm-agent-java/pull/1404
- [x] apm-httpclient11-plugin
- [x] apm-httpclient-core n/a
- [x] apm-java-concurrent-plugin
- [x] apm-jaxrs-plugin https://github.com/elastic/apm-agent-java/pull/1374
- [x] apm-jaxws-plugin elastic/apm-agent-java#1383
- [x] apm-jdbc-plugin
- [x] apm-jms-plugin https://github.com/elastic/apm-agent-java/pull/1394
- [x] apm-jmx-plugin N/A
- [x] apm-jsf-plugin https://github.com/elastic/apm-agent-java/pull/1405
- [x] apm-kafka-plugin #2095 
- [x] apm-log-correlation-plugin N/A
- [x] apm-log-shipper-plugin N/A
- [x] apm-micrometer-plugin
- [x] apm-mongoclient-plugin https://github.com/elastic/apm-agent-java/pull/1369
- [x] apm-okhttp-plugin https://github.com/elastic/apm-agent-java/pull/1368
- [x] apm-opentracing-plugin #1410
- [x] apm-process-plugin
- [x] apm-profiling-plugin N/A
- [x] apm-quartz-job-plugin https://github.com/elastic/apm-agent-java/pull/1366
- [x] apm-redis-plugin #2090
- [x] apm-scala-concurrent-plugin https://github.com/elastic/apm-agent-java/pull/1367
- [x] apm-scheduled-annotation-plugin https://github.com/elastic/apm-agent-java/pull/1364
- [x] apm-servlet-plugin
- [x] apm-spring-resttemplate-plugin https://github.com/elastic/apm-agent-java/pull/1363
- [x] apm-spring-webmvc-plugin https://github.com/elastic/apm-agent-java/pull/1365
- [x] apm-urlconnection-plugin
- [x] trace_methods instrumentation #2094 

Prerequisite for elastic/apm-agent-java#1338 and elastic/apm-agent-java#1339

**Comment by samilAyoub** [comment]
@felixbarny i'm new in this project, what indy plugins mean?

**Comment by SylvainJuge** [comment]
Hi @samilAyoub, it's a new architecture for plugins that is both simpler to implement and less verbose. We have to migrate all existing plugins to this architecture, but it's mostly a technical migration.

**Comment by samilAyoub** [comment]
@SylvainJuge thank you. How do you think we can improve apm-httpclient-core?
