### ISSUE TITLE
Testing Agent attach with Fleet

### ISSUE THREAD

**Issue by AlexanderWert** [elastic/apm-agent-java#2196]

**Comment by eyalkoren** [comment]
## Stage I - integration between APM Server and the agent cli
Testing APM Server 8.x with a config such as:
```yml
  java_attacher:
    enabled: true
    download-agent-version: 1.27.1
    discovery-rules:
    - include-main: opbeans
    - exclude-main: ".*"
    config:
      server_url: "<MY-APM-SERVER-URL>"
      secret_token: "XXXXXXXXXXXXXXXX"
```
- [x] test with `enabled: true/false`
- [x] test `download-agent-version` with multiple versions
- [x] test `include-user` and `exclude-user`
- [x] test `include-main` and `exclude-main`
- [x] test with `include-vmargs: "elastic.apm.attach=true"`

## Stage II - end-to-end testing through Fleet integrations UI
- [ ] test `download-agent-version` with multiple versions
- [ ] test `include-user` and `exclude-user`
- [ ] test `include-main` and `exclude-main`
- [ ] test attachment with the default rule `include-vmargs: "elastic.apm.attach=true"`

**Comment by eyalkoren** [comment]
This issue should not have been closed, we still have stage II that we can now proceed to - https://github.com/elastic/kibana/pull/119131#issuecomment-998194985

**Comment by felixbarny** [comment]
We can proceed with this once https://github.com/elastic/kibana/issues/127414 is resolved.

**Comment by jackshirazi** [comment]
On windows (everything running on Windows) the attach from fleet failed

```
13:24:09.785
elastic_agent.apm_server
[elastic_agent.apm_server][error] Failed to download requested agent version 1.27.1, please double-check your --download-agent-version setting.
13:24:09.824
elastic_agent.apm_server
[elastic_agent.apm_server][error] failed to run java attacher: exit status 1
```

I tried manually running from the Administrator command console, using a manually downloaded `apm-agent-attach-cli-1.30.0.jar` 

```
java -jar apm-agent-attach-cli-1.30.0.jar --exclude-user root --include-vmarg elastic.apm.attach=true --config server_url=http://localhost:8200
```

This failed as the administrator path had an old (1.6) incompatible version of JVM that failed to run the jar

When I explicitly used a compatible JVM version (still from the Administrator command console), the attach succeeded and the APM tabs started being populated with data from the attached service (the service was running under a different user)

**Comment by jackshirazi** [comment]
It seems to me the best option is to always use the JVM that the target service is running, to run the attacher

**Comment by felixbarny** [comment]
We could implement the java process detection in go and then run an attacher either in non-continuous mode with a specific `--pid` or in continuous mode per user that runs a java process.

We do something similar today with the `co.elastic.apm.attach.JvmDiscoverer.UsingPs` in the attacher itself. However, we augment that with `co.elastic.apm.attach.JvmDiscoverer.ForHotSpotVm` but that would also be easy to implement in Go.

**Comment by jackshirazi** [comment]
I think your non-continuous one sounds right.

I feel like if I was designing this from scratch I would have
1. server process running as root that continuously scans for (or gets notifies of, if the OS supports that) Java processes, identifying the userID, PID and the java executable used
2. On finding one, spawn an attacher which runs as the userID using the found executable to attach the agent to the PID, then exit

If I understand the current setup, we have a monitoring server (in go) which spawns a second monitoring process (in java running under an unspecified JVM version) which in turn spawns an attacher process (or does it attach directly)? Regardless, having 2 monitoring services seems wrong, and running the attacher using JVM/userID that is not the target one seems wrong

**Comment by jackshirazi** [comment]
> Do you think this makes sense, or we should keep disabled until implementing a proper discovery for Windows? 

I think the windows continuous mode assumes that the java executable is the current user's one from their environment, so it might succeed, might not, depends on the host setup

> Can we assume there are valid scenarios where it would work? 

Yes, when the java executable is one that works for the target - though even here it might not be the one the customer expects

> What privileges does the Elastic agent runs with on Windows? 

It's running as admin "NT AUTHORITY\SYSTEM "

> Is it equivalent to running as administrator, in which case it may work if the default administrator JVM is a valid one?

Yes

**Comment by eyalkoren** [comment]
Tested on macOS (M1 chip) and Amazon Linux.
On macOS - discovery doesn't work, getting "unimplemented" with regard to the go-sysinfo library because it relies on cgo, which is not built into the APM Server
On Amazon Linux things work as expected, except from `download-agent-version`, where the proper command is used to start the attacher, but eventually the latest agent version gets attached.

**Comment by SylvainJuge** [comment]
Manually testing on Ubuntu 22.04 with stack version `8.4.0-60171339`

- the incude/exclude rules seem to work as expected
- the agent version set in Kibana is ignored, it's always the latest version of the agent that gets attached (to me it's same as #2726).
- the user that starts the attach process is the `root` user (requires #2727 to include this information in logs), whereas the apm-server should execute the attach process with the same user as the running JVM (so the attacher does not have to fork/sudo itself).
- we get a `ClassNotFoundException` unless the permissions of parent folders are altered with `chmod o+x /opt/Elastic/Agent /opt/Elastic/Agent/data /opt/Elastic/Agent/data/elastic-agent-*` to allow directory traversal. This is very probably a side-effect of having the attach process use the `root` user and needs to be checked once we have fixed the attach user.

**Comment by eyalkoren** [comment]
Expected status after merging https://github.com/elastic/apm-server/pull/8803:
- Linux: should be fully supported
- Windows: only supported when the Elastic agent is ran by the same user that runs the monitored Java application. https://github.com/elastic/apm-server/issues/8660 tracks the progress of getting to full Windows support
- macOS: not supported. The first part that is currently missing is the JVM discovery, which should be fixed by https://github.com/elastic/apm-server/issues/8718. Once this is done, we still need to implement a per-user temp directory discovery.
