### ISSUE TITLE
[META 605] Add span links for message tracing

### ISSUE THREAD

**Issue by felixbarny** [elastic/apm-agent-java#2489]
[![issue details](https://img.shields.io/endpoint?label=meta-issue:&url=https%3A%2F%2Fgiss.app.elstc.co%2Fapi%2Fstatus%2Felastic%2Fapm%2F605)](https://github.com/elastic/apm/issues/605)

[![issue details](https://img.shields.io/endpoint?label=spec-issue:&url=https%3A%2F%2Fgiss.app.elstc.co%2Fapi%2Fstatus%2Felastic%2Fapm%2F606)](https://github.com/elastic/apm/issues/606)

**Comment by eyalkoren** [comment]
Consider adding instrumentation for Spring Kafka batch listener (#2601) and use it as a test case for span links

**Comment by eyalkoren** [comment]
So far, of all supported messaging system clients, only the Kafka plugin had to deal with batch processing. In this plugin, we wrap the batch iteration, allowing us to create a transaction-per-record.
Hopefully, we can apply the same approach for SNS and SQS without the need for special-casing single-message-batches.

Therefore, as far as I can see, the scope of this spec implementation for the Java agent is as follows:
- [ ] Polling spans: if the instrumented polling API returns a message with a `tracecontext` header - add a link to the sender span
- [ ] Record-batch iteration (Kafka plugin): we already instrument `org.apache.kafka.clients.consumer.KafkaConsumer#poll`, which returns `org.apache.kafka.clients.consumer.ConsumerRecords` that we instrument as well to wrap the iteration. We will need to apply different iteration-wrapper strategy for each `ConsumerRecords` instance, based on the state at `OnMetodExit` of the `KafkaConsumer#poll` instrumentation - if there is an active span, the wrapper will only add a link per record with tracecontext to the active span, otherwise- we will use the same wrapper we use now to create transaction per record.


org.apache.kafka.clients.consumer.KafkaConsumer

**Comment by eyalkoren** [comment]
Correction: we also have this one to support similarly to Kafka:
- [ ] [`SpringAmqpBatchMessageListenerInstrumentation`](apm-agent-plugins/apm-rabbitmq/apm-rabbitmq-spring/src/main/java/co/elastic/apm/agent/rabbitmq/SpringAmqpBatchMessageListenerInstrumentation.java)

**Comment by trentm** [comment]
> We can either iterate over the list for that, or wrap the list with our own, so that we add the links while the application is iterating.

I'm not sure how strict this rule is, but the [OTel spec on span links](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/api.md#specifying-links) says that `Links cannot be added after Span creation.` My understanding of their reasoning for that is that all span links are passed into the OTel SDK's "Sampling" API so that the registered Sampling implementation can use those links in its processing.  I'm not sure if any of this applies to your "we add the links while the application is iterating".

**Comment by eyalkoren** [comment]
Thanks for pointing out!
I am not even sure there is a meaningful advantage for us in doing that through iteration vs. at batch processing start.
Either way, we discussed it yesterday and decided there are two approaches we would apply:
1. create an encapsulation batch processing span/transaction, where we can typically add links at creation time, as in Lambda triggered by SNS/SQS, or if we instrument a batch processing API like [`org.springframework.amqp.core.MessageListener#onMessageBatch(List)`](https://github.com/elastic/apm-agent-java/blob/2a60d89e8d981c34b41cf4fd417eb938662c8873/apm-agent-plugins/apm-rabbitmq/apm-rabbitmq-spring/src/main/java/co/elastic/apm/agent/rabbitmq/SpringAmqpBatchMessageListenerInstrumentation.java)
2. create a span-per-message if our instrumentation already supports batch-iteration instrumentation with a single span link (added at creation time), **_if there is an active transaction when the iteration starts_**. For example, in #2601, a user asked for inherent instrumentation for a Spring batch processing wrapper around Kafka's polling client API. If we add such instrumentation, we can do as described in 1. However, if we don't add such and the user adds a manual encapsulating batch-processing transaction, as described in the issue, then we will create a span per Kafka record with a link to the sending span.

So I think we are OK with this guidance.

**Comment by eyalkoren** [comment]
@trentm the said above is true for transactions. However, adding span links to message-polling spans cannot typically follow this guidance, as by nature, polling APIs return the received message only at exit time. Assuming that we want polling span to measure the polling duration, it means that we create and start the span on polling method entry and end it on exit, which is only when we can look for the sender's tracecontext.
I am doing exactly this now. If you think that is an issue, let me know and we'll see what we can do about that.

**Comment by trentm** [comment]
@eyalkoren  https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/messaging.md#batch-receiving shows an example from OTel where there are separate spans for "message receive" and "message processing". In their example they add a span link on the "message processing" span. I don't know if that is relevant or useful for the case you describe.  (I vaguely recall some discussion about how to model spans for messaging systems back when Russ was adding Azure support, but I wasn't following very closely at the time.)

> If you think that is an issue

I suspect that it is probably fine to add span links late (after span creation) for our agents, if necessary. https://github.com/open-telemetry/opentelemetry-specification/issues/454 is an OTel Spec discussion on potentially (re-)allowing this.

**Comment by eyalkoren** [comment]
This OTel example is about a poll action that takes place **when there is no active context**. The guidance is then to create an orphan span for the receive action and a child span per message with a single span link. I don't mind doing that once our UI properly renders distributed traces based on links. But as it is now, if I change our tracing to do that, it will be an unfortunate breaking change for our existing users, as it will break their currently properly-presented full traces, because there will be no parent-child relationships to represent the distributed trace. 
In the Java agent we actually have a distinction between receive transactions and message-handling transaction. The former type is discarded by default. 

What I referred to is a polling **span**, i.e.- a polling action traced **when there is an active context (transaction/span)**. As opposed to the former scenario, in this one there is no incentive to do all kind of sophisticated and risky assumptions to trace message handling as it will be automatically traced as child actions of the active transaction/span.
