### ISSUE TITLE
[META] External plugins - Enhancements

### ISSUE THREAD

**Issue by AlexanderWert** [elastic/apm-agent-java#2654]
In 
- https://github.com/elastic/apm-agent-java/issues/937 

we covered the first iteration of supporting external plugins.

This issue collects potential further enhancements for the external plugins support: 
- [ ] https://github.com/elastic/apm-agent-java/issues/2201
- [ ] https://github.com/elastic/apm-agent-java/issues/2200
- [ ] https://github.com/elastic/apm-agent-java/issues/2330

**Comment by AlexanderWert** [comment]
@jackshirazi Are all of the above sub-issues still relevant, or can we close some of them already?

**Comment by jackshirazi** [comment]
I would say any refactorings should be driven by the community, so I've closed that. The other two are still valid
