### ISSUE TITLE
[META 659] Backend dependencies granularity for NoSQL and Messaging

### ISSUE THREAD

**Issue by elastic-apm-tech** [elastic/apm-agent-java#2711]
See meta issue for the description and details:
- Meta issue: https://github.com/elastic/apm/issues/659

### Checklist

- [x] Capture `db.instance` for mongodb (already done)
- [x] Capture `db.instance` for Cassandra: https://github.com/elastic/apm-agent-java/pull/2684
- [x] Capture `db.instance` for Elasticsearch (with heuristic) https://github.com/elastic/apm-agent-java/pull/2796
