### ISSUE TITLE
[META 757] Baggage in APM Agents

### ISSUE THREAD

**Issue by elastic-apm-tech** [elastic/apm-agent-java#3004]
See meta issue and spec for the description and details:
- Meta issue: https://github.com/elastic/apm/issues/757
- Spec issue: https://github.com/elastic/apm/issues/758

**Comment by JonasKunz** [comment]
Implementation plan:
 - [ ] move capability of starting spans from `AbstractSpan` to `ElasticContext` (otherwise baggage updates might be lost)
 - [ ] move header context propagation responibility from `AbstractSpan` to `ElasticContext`, context propagation needs to happen even if no span is active (e.g. propagating just baggage)
 - [ ] Implement baggage in `ElasticContext`, implement header propagation for baggage
 - [ ] Adjust our in-process context propagation to propagate contexts instead of spans
 - [ ] Bridge OpenTelemetry baggage to our internal baggage implementation

**Comment by JonasKunz** [comment]
The implementation will have the following limitations:
 * When creating spans via `ElasticAPM.currentSpan().createSpan()` baggage updates which happened after the activation of the current span will not be visible on the child span. This should not be a problem though, as baggage can only be updated via the OpenTelemetry API. In that case, users should be using the OpenTelemetry API for creating spans aswell.
 * The same limitation applies to our OpenTracing bridge
 * Baggage propagation support has *not* been implemented for Kafka. This will be done via #3017
