### ISSUE TITLE
Add support for capturing HTTP Client request bodies

### ISSUE THREAD

**Issue by JonasKunz** [elastic/apm-agent-java#3725]
Our agent has the capability to capture HTTP request bodies for server frameworks (e.g. servlet api).
A requested feature is to also capture the first few (e.g. 1024) bytes of HTTP client request bodies aswell:

- [x] Add request body capturing support for Apache HTTP Client v4 #3692 
- [x] Add request body capturing support for HttpUrlConnection #3724 
- [x] Add request body capturing support for Spring WebClient #3754 
- [x] Add request body capturing support for Apache HTTP Client v5 #3767 
- [x] Decide on how the data is tranferred to APM-server (e.g. dedicated IntakeV2 field or otel attirbute) and how it is stored    
        - we decided to keep it in `labels` for now as the feature is experimental anyway
- [x] Respect the charset from the `Content-Type` header when converting the bytes back to strings #3726
