### ISSUE TITLE
[meta][docs] Documentation restructure

### ISSUE THREAD

**Issue by bmorelli25** [elastic/apm-agent-java#943]
A meta issue for tracking documentation improvements outlined in https://github.com/elastic/apm-dev/issues/425.

### Doc restructure
- [x] `master` - https://github.com/elastic/apm-agent-java/pull/944
- [x] `1.x` - **Will happen during the next release**

### Build release notes to docs: 
More details: https://github.com/elastic/apm/issues/132.
The PRs in each group must be merged at the same time to prevent breaking the doc build.

#### `master`
- [x] apm-agent-java - https://github.com/elastic/apm-agent-java/pull/945
- [x] docs - https://github.com/elastic/docs/pull/1458

#### `1.x`
- [x] Temporary backport of placeholder changelog file. This will allow us to merge https://github.com/elastic/docs/pull/1459, and thus prevent the doc build from breaking during the next release - https://github.com/elastic/apm-agent-java/pull/948
- [x] docs - https://github.com/elastic/docs/pull/1459
